name: Build Skeleton

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Skeleton Package
        uses: w00fz/skeleton-builder@main
      - uses: xresloader/upload-to-github-release@v1
        with:
          file: "/build/*.zip"
          tags: true
          overwrite: true
          
