name: Build Skeleton

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Skeleton Package
        uses: w00fz/skeleton-builder@v1.0.0
          
