name: Tirgger Skeletons Build

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Target tag for re-upload'     
        required: true
        default: ''
      version:
        description: 'Which Grav release to use'
        required: true
        default: 'latest'
      admin:
        description: 'Create also a package with Admin'
        required: true
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SKELETONS=`curl -s "${{secrets.SKELETONS_JSON_LIST}}"`
      WORKFLOW="build-skeleton.yml"
      AUTH=":${{secrets.GLOBAL_TOKEN}}"
    steps:
      - uses: actions/checkout@v2
      - name: Make it rain ☔️
        run: |
          echo $SKELETONS | jq -r '.[]' | while read SKELETON; do
            KEY=$(echo "$SKELETON" | jq -cr 'keys[0]')
            VERSION=$(echo "$SKELETON" | jq -cr '.[]')
            URL="https://api.github.com/repos/${KEY}/actions/workflows/${WORKFLOW}/dispatches"
            
            curl -XPOST -u "${AUTH}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Content-Type: application/json" ${URL} \
            --data '{ "ref": "master", 
                      "inputs": { 
                        "tag": "'"$VERSION"'"", 
                        "version": "'"$INPUT_VERSION"'", 
                        "admin": "'"$INPUT_ADMIN"'" 
                      } 
                    }'
            echo "Dispatched Worfklow for ${KEY}@$VERSION"
          done
